<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\card_back.png" />
    <None Remove="images\card_clubs_ace.png" />
    <None Remove="images\card_clubs_eight.png" />
    <None Remove="images\card_clubs_five.png" />
    <None Remove="images\card_clubs_four.png" />
    <None Remove="images\card_clubs_jack.png" />
    <None Remove="images\card_clubs_king.png" />
    <None Remove="images\card_clubs_nine.png" />
    <None Remove="images\card_clubs_queen.png" />
    <None Remove="images\card_clubs_seven.png" />
    <None Remove="images\card_clubs_six.png" />
    <None Remove="images\card_clubs_ten.png" />
    <None Remove="images\card_clubs_three.png" />
    <None Remove="images\card_clubs_two.png" />
    <None Remove="images\card_diamonds_ace.png" />
    <None Remove="images\card_diamonds_eight.png" />
    <None Remove="images\card_diamonds_five.png" />
    <None Remove="images\card_diamonds_four.png" />
    <None Remove="images\card_diamonds_jack.png" />
    <None Remove="images\card_diamonds_king.png" />
    <None Remove="images\card_diamonds_nine.png" />
    <None Remove="images\card_diamonds_queen.png" />
    <None Remove="images\card_diamonds_seven.png" />
    <None Remove="images\card_diamonds_six.png" />
    <None Remove="images\card_diamonds_ten.png" />
    <None Remove="images\card_diamonds_three.png" />
    <None Remove="images\card_diamonds_two.png" />
    <None Remove="images\card_empty.png" />
    <None Remove="images\card_hearts_ace.png" />
    <None Remove="images\card_hearts_eight.png" />
    <None Remove="images\card_hearts_five.png" />
    <None Remove="images\card_hearts_four.png" />
    <None Remove="images\card_hearts_jack.png" />
    <None Remove="images\card_hearts_king.png" />
    <None Remove="images\card_hearts_nine.png" />
    <None Remove="images\card_hearts_queen.png" />
    <None Remove="images\card_hearts_seven.png" />
    <None Remove="images\card_hearts_six.png" />
    <None Remove="images\card_hearts_ten.png" />
    <None Remove="images\card_hearts_three.png" />
    <None Remove="images\card_hearts_two.png" />
    <None Remove="images\card_joker_black.png" />
    <None Remove="images\card_joker_red.png" />
    <None Remove="images\card_spades_ace.png" />
    <None Remove="images\card_spades_eight.png" />
    <None Remove="images\card_spades_five.png" />
    <None Remove="images\card_spades_four.png" />
    <None Remove="images\card_spades_jack.png" />
    <None Remove="images\card_spades_king.png" />
    <None Remove="images\card_spades_nine.png" />
    <None Remove="images\card_spades_queen.png" />
    <None Remove="images\card_spades_seven.png" />
    <None Remove="images\card_spades_six.png" />
    <None Remove="images\card_spades_ten.png" />
    <None Remove="images\card_spades_three.png" />
    <None Remove="images\card_spades_two.png" />
    <None Remove="images\game_background.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\card_back.png" />
    <Resource Include="images\card_clubs_ace.png" />
    <Resource Include="images\card_clubs_eight.png" />
    <Resource Include="images\card_clubs_five.png" />
    <Resource Include="images\card_clubs_four.png" />
    <Resource Include="images\card_clubs_jack.png" />
    <Resource Include="images\card_clubs_king.png" />
    <Resource Include="images\card_clubs_nine.png" />
    <Resource Include="images\card_clubs_queen.png" />
    <Resource Include="images\card_clubs_seven.png" />
    <Resource Include="images\card_clubs_six.png" />
    <Resource Include="images\card_clubs_ten.png" />
    <Resource Include="images\card_clubs_three.png" />
    <Resource Include="images\card_clubs_two.png" />
    <Resource Include="images\card_diamonds_ace.png" />
    <Resource Include="images\card_diamonds_eight.png" />
    <Resource Include="images\card_diamonds_five.png" />
    <Resource Include="images\card_diamonds_four.png" />
    <Resource Include="images\card_diamonds_jack.png" />
    <Resource Include="images\card_diamonds_king.png" />
    <Resource Include="images\card_diamonds_nine.png" />
    <Resource Include="images\card_diamonds_queen.png" />
    <Resource Include="images\card_diamonds_seven.png" />
    <Resource Include="images\card_diamonds_six.png" />
    <Resource Include="images\card_diamonds_ten.png" />
    <Resource Include="images\card_diamonds_three.png" />
    <Resource Include="images\card_diamonds_two.png" />
    <Resource Include="images\card_empty.png" />
    <Resource Include="images\card_hearts_ace.png" />
    <Resource Include="images\card_hearts_eight.png" />
    <Resource Include="images\card_hearts_five.png" />
    <Resource Include="images\card_hearts_four.png" />
    <Resource Include="images\card_hearts_jack.png" />
    <Resource Include="images\card_hearts_king.png" />
    <Resource Include="images\card_hearts_nine.png" />
    <Resource Include="images\card_hearts_queen.png" />
    <Resource Include="images\card_hearts_seven.png" />
    <Resource Include="images\card_hearts_six.png" />
    <Resource Include="images\card_hearts_ten.png" />
    <Resource Include="images\card_hearts_three.png" />
    <Resource Include="images\card_hearts_two.png" />
    <Resource Include="images\card_joker_black.png" />
    <Resource Include="images\card_joker_red.png" />
    <Resource Include="images\card_spades_ace.png" />
    <Resource Include="images\card_spades_eight.png" />
    <Resource Include="images\card_spades_five.png" />
    <Resource Include="images\card_spades_four.png" />
    <Resource Include="images\card_spades_jack.png" />
    <Resource Include="images\card_spades_king.png" />
    <Resource Include="images\card_spades_nine.png" />
    <Resource Include="images\card_spades_queen.png" />
    <Resource Include="images\card_spades_seven.png" />
    <Resource Include="images\card_spades_six.png" />
    <Resource Include="images\card_spades_ten.png" />
    <Resource Include="images\card_spades_three.png" />
    <Resource Include="images\card_spades_two.png" />
    <Resource Include="images\game_background.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
